server:
  ip: localhost
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school?serverTimezone=GMT%2b8
    username: root
    password: 123456
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379

  servlet:
      multipart:
        max-file-size: 100MB
        max-request-size: 100MB

  #spring.jackson.date-format=yyyy-MM-dd

  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER

mybatis:
  mapper-locations: classpath:mapper/*.xml     #扫描mapper.xml文件
#     configuration:
#      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


files:
  upload:
    path: C:/Users/cgc13/IdeaProjects/springboot/files/
    #    path: /home/files/